/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeStore {
  close(): void
  status(): JsStatus
}

export declare function authorityCreateSpace(store: NativeStore, spaceKey: string): string

export declare function authorityMutate(store: NativeStore, request: JsCreateMemoryRequest): string

export declare function authorityRevise(store: NativeStore, request: JsReviseMemoryRequest): JsMemoryMutation

export declare function cancelOperation(store: NativeStore, operationId: string): void

export declare function closeStore(store: NativeStore): void

export declare function feedbackSubmit(store: NativeStore, request: JsFeedbackSubmission): JsFeedbackCommit

export interface JsCreateMemoryRequest {
  spaceId: string
  documentKey?: string
  idempotencyKey?: string
  mdx: string
}

export interface JsEnrichmentProjection {
  version: number
  inputHash: string
  spaceId: string
  memoryId: string
  revisionId: string
  semanticNodeId?: string
  content: string
  maxTags: number
}

export interface JsFeedbackCommit {
  generation: string
  events: Array<JsFeedbackEventResult>
}

export interface JsFeedbackEvent {
  resultId: string
  outcome: string
}

export interface JsFeedbackEventResult {
  eventId: string
  generation: string
  retrievalId: string
  spaceId: string
  memoryId: string
  revisionId: string
  semanticNodeId?: string
  outcome: string
  occurredAtSeconds: number
}

export interface JsFeedbackSubmission {
  retrievalId: string
  idempotencyKey: string
  events: Array<JsFeedbackEvent>
}

export interface JsMemoryMutation {
  memoryId: string
  spaceId: string
  revisionId: string
  authorityGeneration: string
}

export interface JsProviderItem {
  key: string
  text: string
}

export interface JsProviderResult {
  workId: string
  accepted: boolean
  scores?: Array<JsRerankScore>
  tags?: Array<string>
}

export interface JsProviderWork {
  workId: string
  workType: string
  signature: string
  dimensions: number
  items: Array<JsProviderItem>
  query?: string
  candidates: Array<string>
  projection?: JsEnrichmentProjection
}

export interface JsQueryRequest {
  scope: Array<string>
  text?: string
}

export interface JsQueryResponse {
  resultCount: number
  authorityGeneration: string
  degraded: boolean
  retrievalId: string
  results: Array<JsQueryResult>
}

export interface JsQueryResult {
  resultId: string
  spaceId: string
  memoryId: string
  revisionId: string
}

export interface JsRerankScore {
  handle: string
  score: number
}

export interface JsReviseMemoryRequest {
  memoryId: string
  expectedHead: string
  mdx: string
}

export interface JsStatus {
  authorityGeneration: string
  baseCoverage: string
  semanticCoverage: string
  activeReadLeases: number
  closed: boolean
}

export declare function openStore(dataDir: string): NativeStore

export declare function providerPollWork(store: NativeStore): JsProviderWork | null

export declare function providerSubmitResult(store: NativeStore, result: JsProviderResult): void

export declare function queryResume(store: NativeStore, operationId: string): JsQueryResponse

export declare function queryStart(store: NativeStore, request: JsQueryRequest): JsQueryResponse

export declare function readSessionClose(store: NativeStore, sessionId: string): void

export declare function readSessionOpen(store: NativeStore, request: JsQueryRequest): string
