/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeStore {
  close(): void
  status(): JsStatus
}

export declare function authorityMutate(store: NativeStore, request: JsCreateMemoryRequest): string

export declare function cancelOperation(store: NativeStore, operationId: string): void

export declare function closeStore(store: NativeStore): void

export interface JsCreateMemoryRequest {
  spaceId: string
  documentKey?: string
  mdx: string
}

export interface JsProviderResult {
  workId: string
  accepted: boolean
}

export interface JsQueryRequest {
  scope: Array<string>
  text?: string
}

export interface JsQueryResponse {
  resultCount: number
  authorityGeneration: string
  degraded: boolean
}

export interface JsStatus {
  authorityGeneration: string
  baseCoverage: string
  semanticCoverage: string
  activeReadLeases: number
  closed: boolean
}

export declare function openStore(dataDir: string): NativeStore

export declare function providerPollWork(store: NativeStore): string | null

export declare function providerSubmitResult(store: NativeStore, result: JsProviderResult): void

export declare function queryResume(store: NativeStore, operationId: string): JsQueryResponse

export declare function queryStart(store: NativeStore, request: JsQueryRequest): JsQueryResponse

export declare function readSessionClose(store: NativeStore, sessionId: string): void

export declare function readSessionOpen(store: NativeStore, request: JsQueryRequest): string
