[package]
name = "memoria-query"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
memoria-types = { version = "0.1.0", path = "../memoria-types" }
memoria-mdx = { version = "0.1.0", path = "../memoria-mdx" }
memoria-derived = { version = "0.1.0", path = "../memoria-derived" }
thiserror = "2.0.20"

[dev-dependencies]
memoria-derived = { version = "0.1.0", path = "../memoria-derived" }
tempfile = "3.27.0"
